INSERT INTO dbo.SpeciesLookup VALUES (1, 'Mute Swan',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bewick''s Swan',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Whooper Swan',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bean Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Taiga Bean Goose (fabalis)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Tundra Bean Goose (rossicus)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pink-footed Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'White-fronted Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Greenland White-fronted Goose (flavirostris)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'European White-fronted Goose (albifrons)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Lesser White-fronted Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Greylag Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Canada Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Barnacle Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Brent Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Pale-bellied Brent Goose (hrota)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Dark-bellied Brent Goose (bernicla)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Egyptian Goose',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Shelduck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Mandarin Duck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wigeon',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Gadwall','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Teal','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Green-winged Teal',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Mallard',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pintail',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Garganey','5/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Shoveler','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-crested Pochard',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pochard',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ferruginous Duck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Tufted Duck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Scaup',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Eider',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'King Eider',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Long-tailed Duck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Common Scoter',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Surf Scoter',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Velvet Scoter',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Goldeneye',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Smew',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-breasted Merganser','4/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Goosander',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ruddy Duck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red Grouse','4/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black Grouse',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Northern Bobwhite',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-legged Partridge',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Grey Partridge','3/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Quail','5/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pheasant',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-throated Diver',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black-throated Diver',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Northern Diver',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Grebe','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Crested Grebe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-necked Grebe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Slavonian Grebe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black-necked Grebe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Fulmar',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Cory’s Shearwater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Shearwater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sooty Shearwater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Manx Shearwater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Balearic Shearwater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Macaronesian Shearwater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Storm-petrel',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Leach’s Storm-petrel',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Gannet',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Cormorant',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Continental Cormorant (sinensis)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Shag',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Magnificent Frigatebird',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bittern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Bittern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Night Heron',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Egret','4/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great White Egret',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Grey Heron',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Purple Heron',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Spoonbill',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Honey-buzzard',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black Kite',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red Kite',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'White-tailed Eagle',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Marsh Harrier',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hen Harrier','3/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Goshawk','2/14/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sparrowhawk','3/1/2017','8/15/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Buzzard','3/15/2017','8/30/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rough-legged Buzzard',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Golden Eagle',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Osprey',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Kestrel','4/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-footed Falcon',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Merlin','3/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hobby',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Gyr Falcon',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Peregrine Falcon','3/1/2017','7/15/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Water Rail','5/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Spotted Crake',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Baillon’s Crake',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Corn Crake','5/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Moorhen',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Coot',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Common Crane',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Oystercatcher',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Avocet',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Stone-curlew',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Ringed Plover',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ringed Plover',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Tundra Ringed Plover (tundrae)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Kentish Plover',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Dotterel',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'American Golden Plover',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Golden Plover','5/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Grey Plover',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Lapwing',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Knot',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sanderling',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Stint',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Temminck’s Stint',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pectoral Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Curlew Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Purple Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Dunlin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Buff-breasted Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ruff',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Jack Snipe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Snipe','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Snipe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Long-billed Dowitcher',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Woodcock','3/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black-tailed Godwit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Icelandic Black-tailed Godwit (islandica)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'European Black-tailed Godwit (limosa)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bar-tailed Godwit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Whimbrel',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Curlew',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Spotted Redshank',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Redshank',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Greenshank',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Lesser Yellowlegs',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Green Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wood Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Common Sandpiper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Turnstone',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wilson’s Phalarope',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-necked Phalarope',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Grey Phalarope',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pomarine Skua',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Arctic Skua',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Long-tailed Skua',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Skua',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Mediterranean Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sabine’s Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black-headed Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ring-billed Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Common Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Lesser Black-backed Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Scandinavian Lesser Black-backed Gull (intermedius)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Caspian Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Yellow-legged Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Herring Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Northern (Scandinavian) Herring Gull (argentatus)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Iceland Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Kumlien''s Iceland Gull (kumlieni)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Glaucous Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Black-backed Gull',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Kittiwake',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bridled Tern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Tern','5/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black Tern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sandwich Tern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Common Tern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Roseate Tern',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Arctic Tern','5/15/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Guillemot',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Razorbill',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black Guillemot',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Auk',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Puffin','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pallas’s Sandgrouse',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rock Dove',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Feral Pigeon',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Stock Dove','4/15/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Woodpigeon',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Collared Dove',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Turtle Dove',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Mourning Dove',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rose-ringed Parakeet',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Spotted Cuckoo',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Cuckoo',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Yellow-billed Cuckoo',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Barn Owl','3/1/2017','9/30/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Scops Owl',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Horned Owl',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Snowy Owl',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Owl',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Tawny Owl','2/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Long-eared Owl','2/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Short-eared Owl','2/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Nightjar',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Swift',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Alpine Swift',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Kingfisher','4/15/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bee-eater',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Roller',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hoopoe',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wryneck',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Green Woodpecker',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Spotted Woodpecker',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Calandra Lark',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wood Lark',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Skylark',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Shore Lark',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sand Martin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Swallow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'House Martin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Richard’s Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Tawny Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Olive-backed Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Tree Pipit','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pechora Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Meadow Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rock Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Scandinavian Rock Pipit (littoralis)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Water Pipit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Yellow Wagtail',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Blue-headed Yellow Wagtail (flava)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Grey Wagtail',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pied Wagtail',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'White Wagtail (alba)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Waxwing',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Dipper','3/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wren',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Dunnock',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Robin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Thrush Nightingale',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Nightingale',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bluethroat',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'White-throated Robin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black Redstart',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Redstart','4/15/2017','6/30/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Whinchat','5/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Stonechat',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wheatear',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black-eared Wheatear',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Desert Wheatear',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ring Ouzel','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Blackbird',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Fieldfare',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Song Thrush',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Redwing',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Icelandic Redwing (coburni)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Mistle Thrush',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Grasshopper Warbler','5/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Aquatic Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sedge Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Marsh Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Reed Warbler','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Icterine Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Melodious Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Blackcap',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Garden Warbler','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Barred Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Lesser Whitethroat','4/15/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Siberian Lesser Whitethroat (blythi)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Central Asian Lesser Whitehtroat (halimodendri)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Whitethroat',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Subalpine Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Western Subalpine Warbler (cantillans)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Eastern Subalpine Warbler (albistriata)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Sardinian Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Greenish Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pallas’s Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Yellow-browed Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hume''s Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Dusky Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Western Bonelli''s Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Eastern Bonelli''s Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Wood Warbler','4/15/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Chiffchaff',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Siberian Chiffchaff (tristis)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Willow Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Goldcrest',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Firecrest','4/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Spotted Flycatcher',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-breasted Flycatcher',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Pied Flycatcher',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bearded Tit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-winged Laughing Thrush',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Long-tailed Tit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Blue Tit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Tit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Coal Tit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Marsh Tit',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Nuthatch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Treecreeper',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Golden Oriole',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-backed Shrike',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Great Grey Shrike',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Steppe (Mauryan) Grey Shrike',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Woodchat Shrike',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Jay',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Magpie',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Chough','3/14/2017','7/15/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Jackdaw',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Nordic (Eastern) Jackdaw (monedula/soemmerringii)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rook',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Carrion Crow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hooded Crow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hybrid Hooded x Carrion Crow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Raven',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Starling',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rosy Starling',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'House Sparrow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Tree Sparrow','3/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Chaffinch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Brambling',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Serin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Greenfinch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Goldfinch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Siskin',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Linnet',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Twite',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Redpoll',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Lesser Redpoll (cabaret)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (2, 'Common (Mealy) Redpoll (flammea)',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Arctic Redpoll',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Common Crossbill',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Scarlet Rosefinch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Bullfinch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Hawfinch',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Yellow-rumped Warbler',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Song Sparrow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'White-throated Sparrow',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Lapland Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Snow Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Yellowhammer','3/1/2017','7/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Cirl Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Ortolan Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Rustic Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Little Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Reed Bunting','5/1/2017','8/31/2017')
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Red-headed Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Black-headed Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Corn Bunting',NULL,NULL)
INSERT INTO dbo.SpeciesLookup VALUES (1, 'Baltimore Oriole',NULL,NULL)